import { collection, getDocs } from 'firebase/firestore'
import { Link } from 'react-router-dom'
import { useEffect, useState } from 'react'
import { db } from '../../firebase'
import { services, specialDeals as defaultSpecialDeals } from '../data'

function Home() {
  const [specialDeals, setSpecialDeals] = useState(defaultSpecialDeals)
  useEffect(() => { getDocs(collection(db, 'specials')).then(snapshot => { if (!snapshot.empty) setSpecialDeals(snapshot.docs.map(item => ({ id: item.id, ...item.data() }))) }).catch(() => {}) }, [])
  return <><section className="home-hero"><div className="page-wrap"><p className="eyebrow">Sport science · Cape Town</p><h2>Train with purpose.<br /><span>Move renewed.</span></h2><p className="hero-copy">Evidence-led movement and performance coaching for bodies ready for more.</p><Link className="button button-light" to="/book-now">Book your session <span>↗</span></Link></div></section><section className="deals-section"><div className="page-wrap"><div className="deals-heading"><div><p className="eyebrow green">Limited offers</p><h2>Special<br /><span>deals.</span></h2></div><p className="body-copy">A little more reason to make time for your body. Explore our current offers below.</p></div><div className="deals-list">{specialDeals.map((deal, index) => <article className="deal-row" key={deal.id || deal.title}><span className="deal-number">0{index + 1}</span><div><p className="eyebrow green">{deal.label}</p><h3>{deal.title}</h3>{deal.oldPrice && deal.newPrice && <div className="deal-prices"><span>{deal.oldPrice}</span><strong>{deal.newPrice}</strong></div>}<p>{deal.detail}</p></div><Link className="text-link" to={deal.path}>{deal.action} <span>↗</span></Link></article>)}</div></div></section><section className="page-wrap intro-section"><div><p className="eyebrow green">The renewed approach</p><h2>Performance<br />is personal.</h2></div><div><p className="body-copy">Whether you are recovering from injury, chasing a personal best, or building a body you can rely on, your plan should meet you where you are.</p><Link className="text-link" to="/about">Meet Berucia <span>→</span></Link></div></section><section className="dark-section"><div className="page-wrap"><p className="eyebrow">What we do</p><h2>Built for your<br /><span>next level.</span></h2><div className="service-list">{services.map((service, index) => <div className="service-row" key={service.name}><span>0{index + 1}</span><strong>{service.name}</strong><span>↗</span></div>)}</div></div></section></>
}

export default Home